### ISSUE TITLE
issue getting username from git hub

### ISSUE THREAD

**Issue by newnumtra** [sindresorhus/github-username#11]
Hi Hope you are safe and sound , i ma using npm package github-username to get username by providing email address, the issue is that in some emails this package get username , while in other some other  emails not getting uername by providing email. i dont know ehat is the issue , you can check it , if we provide this email ( sindresorhus@gmail.com) or (hamza007g1@gmail.com) we can get our username or owner name, but if i provide other one email, we can't get username . please help me. Thank you

**Comment by sindresorhus** [comment]
It's now explained in the readme that it's not guaranteed to find a username.
