### ISSUE TITLE
Example does not seem to work

### ISSUE THREAD

**Issue by leszekhanusz** [sindresorhus/github-username#7]
The example does not seem to work for me.

The github api is working correctly manually with the browser.

Nothing is returned (no errors).

In the got package, the eventEmitter sends the response event correctly but apparently in the got package the stream promise is never resolved.

I used these versions:

> └─┬ github-username@4.1.0 
  └─┬ gh-got@6.0.0 
    ├─┬ got@7.1.0 
    │ ├─┬ decompress-response@3.3.0 
    │ │ └── mimic-response@1.0.0 
    │ ├── duplexer3@0.1.4 
    │ ├── get-stream@3.0.0 
    │ ├── is-retry-allowed@1.1.0 
    │ ├── is-stream@1.1.0 
    │ ├─┬ isurl@1.0.0 
    │ │ ├─┬ has-to-string-tag-x@1.4.1 
    │ │ │ └── has-symbol-support-x@1.4.1 
    │ │ └── is-object@1.0.1 
    │ ├── lowercase-keys@1.0.0 
    │ ├── p-cancelable@0.3.0 
    │ ├─┬ p-timeout@1.2.0 
    │ │ └── p-finally@1.0.0 
    │ ├── safe-buffer@5.1.1 
    │ ├── timed-out@4.0.1 
    │ ├─┬ url-parse-lax@1.0.0 
    │ │ └── prepend-http@1.0.4 
    │ └── url-to-options@1.0.1 
    └── is-plain-obj@1.1.0

**Comment by sindresorhus** [comment]
Tests are passing for me. You might over the GitHub rate limit.

**Comment by leszekhanusz** [comment]
I can use the url https://api.github.com/search/users?q=sindresorhus%40gmail.com%20in%3Aemail in the browser and I receive always the correct json

**Comment by leszekhanusz** [comment]
It works with version 4.0.0 but not with version 4.1.0

```
leszek@leszek-desktop:~/Documents/projects/tes_gh$ npm install github-username@4.0.0
npm WARN saveError ENOENT: no such file or directory, open '/home/leszek/Documents/projects/tes_gh/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/leszek/Documents/projects/tes_gh/package.json'
npm WARN tes_gh No description
npm WARN tes_gh No repository field.
npm WARN tes_gh No README data
npm WARN tes_gh No license field.

+ github-username@4.0.0
added 17 packages in 1.404s
leszek@leszek-desktop:~/Documents/projects/tes_gh$ node test.js 
The username is 
sindresorhus
leszek@leszek-desktop:~/Documents/projects/tes_gh$ npm install github-username@4.1.0
npm WARN saveError ENOENT: no such file or directory, open '/home/leszek/Documents/projects/tes_gh/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/leszek/Documents/projects/tes_gh/package.json'
npm WARN tes_gh No description
npm WARN tes_gh No repository field.
npm WARN tes_gh No README data
npm WARN tes_gh No license field.

+ github-username@4.1.0
added 12 packages and updated 1 package in 1.262s
leszek@leszek-desktop:~/Documents/projects/tes_gh$ node test.js 
leszek@leszek-desktop:~/Documents/projects/tes_gh$
```

**Comment by SamVerschueren** [comment]
What `npm` version are you running? It works perfectly fine for me with `4.1.0`.

**Comment by leszekhanusz** [comment]
It is very strange.

It was not working and I was able to do a bisect to see that the problem appeared only after [this commit](https://github.com/sindresorhus/got/commit/578f38d5276d78be33bf55eff2d38b79ed6482d6) in the got package. But it does not make any sense.

But now it is working even with the same non-working version as before.

I don't know what to think. It might be some intermittent network problem and I have been very unlucky.

I suppose you can close this bug if it is not reproducible.
